style: run pre-commit on all files

diff --git a/resources/download_dme_files b/resources/download_dme_files
--- a/resources/download_dme_files
+++ b/resources/download_dme_files
@@ -17,12 +17,12 @@ Usage:
 Synopsis:
   This script provides a high level wrapper to the HPC DME API.
 Given a list of input dme file paths and an API token, it will
-download those files locally to the user provided output path. 
+download those files locally to the user provided output path.
 
 Required Arguments:
-  -f, --files  FILE   [Type: Str]  Files to download from DME. 
+  -f, --files  FILE   [Type: Str]  Files to download from DME.
                                      One or more dme file paths can
-                                     be provided. Multiple files can 
+                                     be provided. Multiple files can
                                      be downloaded at once by providing
                                      a quoted space separated list of files.
   -o, --output OUTPUT [Type: Path] Path to an output directory.
@@ -30,23 +30,23 @@ Required Arguments:
                                      downloaded. If the provided output
                                      directory does not exist, it will be
                                      initialized automatically.
-  -t, --token  TOKEN  [Type: Str]  API token for HPC DME. A text file 
+  -t, --token  TOKEN  [Type: Str]  API token for HPC DME. A text file
                                      containing an API token for DME
-                                     can be provided, or the API token 
+                                     can be provided, or the API token
                                      can be provided as a string.
 Options:
-  -r, --rid    RID    [Type: Str]  Request Identifer. This is an optional 
-                                     string to help track a given request. 
-                                     This identifer is appended to any log 
-                                     files. If a request identifer is not 
-                                     provided, a request identifer will be 
-                                     generated from an MD5 checksum based 
-                                     on the time of the request and the 
-                                     other user provided options. 
-  -p, --proxy PROXY   [Type: Str]  HTTPS Proxy. This option can be used to 
+  -r, --rid    RID    [Type: Str]  Request Identifer. This is an optional
+                                     string to help track a given request.
+                                     This identifer is appended to any log
+                                     files. If a request identifer is not
+                                     provided, a request identifer will be
+                                     generated from an MD5 checksum based
+                                     on the time of the request and the
+                                     other user provided options.
+  -p, --proxy PROXY   [Type: Str]  HTTPS Proxy. This option can be used to
                                      set or override the following environment
-                                     variable: https_proxy. By default, a 
-                                     https proxy will not be utilized unless 
+                                     variable: https_proxy. By default, a
+                                     https proxy will not be utilized unless
                                      it is inherited from a parent shell.
   -h, --help          [Type: Bool] Displays usage and help information.
   -v, --version       [Type: Bool] Displays version information.
@@ -85,8 +85,8 @@ function parser() {
       -f  | --files)  provided "$key" "${2:-}"; Arguments["f"]="$2"; shift; shift;;
       -o  | --output) provided "$key" "${2:-}"; Arguments["o"]="$2"; shift; shift;;
       -t  | --token)  provided "$key" "${2:-}"; Arguments["t"]="$2"; shift; shift;;
-      -r  | --rid)    provided "$key" "${2:-}"; Arguments["r"]="$2"; shift; shift;;  
-      -p  | --proxy)  provided "$key" "${2:-}"; Arguments["p"]="$2"; shift; shift;; 
+      -r  | --rid)    provided "$key" "${2:-}"; Arguments["r"]="$2"; shift; shift;;
+      -p  | --proxy)  provided "$key" "${2:-}"; Arguments["p"]="$2"; shift; shift;;
       -*  | --*) err "Error: Failed to parse unsupported argument: '${key}'."; usage && exit 1;;
       *) err "Error: Failed to parse unrecognized argument: '${key}'. Do any of your inputs have spaces?"; usage && exit 1;;
     esac
@@ -128,9 +128,9 @@ function check(){
 function grab(){
   # Grabs the contents of a file
   # else returns input that was provided
-  # to allow for flexiable API token input 
-  # so a user can directly provide a token 
-  # as a string or point to a file containing 
+  # to allow for flexiable API token input
+  # so a user can directly provide a token
+  # as a string or point to a file containing
   # the token
   # INPUT $1 = token file or string
 
@@ -148,11 +148,11 @@ function grab(){
 
 
 function retry() {
-  # Tries to run a cmd 5 times before failing 
+  # Tries to run a cmd 5 times before failing
   # If a command is successful, it will break out of attempt loop
-  # Failed attempts are padding with the following exponential 
+  # Failed attempts are padding with the following exponential
   # back-off strategy {4, 16, 64, 256, 1024} in seconds
-  # @INPUTS "$@"" = cmd to run 
+  # @INPUTS "$@"" = cmd to run
   # @CALLS timestamp() to log time of encountered error
   # @CALLS err() to redirect logging information to stderr
   # @CALLS fatal() if command cannot be run in 5 attempts
@@ -161,9 +161,9 @@ function retry() {
   local max=5
   local attempt=true # flag for while loop
   while $attempt; do
-    # Attempt command and break if successful 
+    # Attempt command and break if successful
     "$@" && attempt=false || {
-      # Try again up to 5 times 
+      # Try again up to 5 times
       if [[ $n -le $max ]]; then
         err "[$(timestamp)] Command failed: $@"
         delay=$(( 4**$n ))
@@ -180,15 +180,15 @@ function retry() {
 
 function require(){
   # Requires an executable is in $PATH
-  # as a last resort it will attempt to load 
+  # as a last resort it will attempt to load
   # the executable as a module. If an exe is
   # not in $PATH raises fatal().
   # INPUT $1 = executable to check
 
   # Check if $1 in $PATH
   # If not, try to module load $1 as a last resort
-  command -V "$1" &> /dev/null || { 
-    command -V module &> /dev/null && 
+  command -V "$1" &> /dev/null || {
+    command -V module &> /dev/null &&
     module purge && module load "$1"
   } || fatal "Error: failed to find or load '$1', not installed on target system."
 
@@ -196,12 +196,12 @@ function require(){
 
 
 function _id(){
-  # Generates a default request identifer 
+  # Generates a default request identifer
   # if the -r or --rid option is not provided.
   # The default identifer is generated by generating
-  # an md5 checksum of the required user inputs and 
+  # an md5 checksum of the required user inputs and
   # the timestamp
-  
+
   # List of required arguments
   local features
   local identifer
@@ -210,15 +210,15 @@ function _id(){
     value=${Arguments[${arg}]:-}
     features+="${value}"
   done
-  
+
   identifer=$(md5sum <<< "${features}" | awk '{print $1}')
 
   echo "${identifer}"
-} 
+}
 
 
 function _download(){
-  # Downloads a file from HPC DME 
+  # Downloads a file from HPC DME
   # INPUT $1 = File to download from DME
   # INPUT $2 = Local output directory
   # INPUT $3 = DME API token
@@ -226,16 +226,16 @@ function _download(){
   # INPUT $5 = HTTPS Proxy, defaults to no proxy set
   # @CALLS require() to enfore cURL installation
   # @CALLS timestamp() to log time of file download
-  # @CALLS fatal() if curl returns a non-200 http response 
+  # @CALLS fatal() if curl returns a non-200 http response
 
   # Require curl is installed
   require curl
 
   # Check if a proxy needs to be set
   if [[ ! -z "${5:-}" ]]; then export https_proxy="${5}"; fi
-  
+
   # Try to download each file from DME with 5 max attempts
-  for file in ${1// /$'\t'}; do 
+  for file in ${1// /$'\t'}; do
     local fname="$(basename "$file")"
     echo "[$(timestamp) @ ${4}] Downloading '${file}' from HPC DME to '$2/${fname}'"
     response=$(retry \
@@ -251,10 +251,10 @@ function _download(){
                   -w "%{http_code}"
     )
 
-    # Check http response code for any failures 
-    if [ $response != "200" ]; then 
+    # Check http response code for any failures
+    if [ $response != "200" ]; then
       fatal "Error: download request for '$file' failed with http response of '$response'!"
-    fi 
+    fi
 
   done
 }
@@ -278,7 +278,7 @@ function main(){
   requestid="${Arguments[r]:-$(_id)}"
   proxy="${Arguments[p]:-}"
 
-  # Download files from DME to local output directory 
+  # Download files from DME to local output directory
   # INPUT $1 = Files to download from DME
   # INPUT $2 = Local output directory
   # INPUT $3 = DME API token
